#!/bin/bash
#SBATCH -J helloworld
#SBATCH -o helloworld.stdout
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH -p RM-small
#SBATCH -t 00:01:00

# set variable so that task placement works as expected
export I_MPI_JOB_RESPECT_PROCESS_PLACEMENT=0

mpirun -np 4 ./ex1
